export const BULK_REGISTRAR_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_controller', type: 'address', internalType: 'address' },
      { name: '_referrer', type: 'bytes32', internalType: 'bytes32' },
      { name: '_ens', type: 'address', internalType: 'contract ENS' },
      { name: '_owner', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'CONTROLLER',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'contract IETHRegistrarController' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'REFERRER',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'available',
    inputs: [{ name: 'names', type: 'string[]', internalType: 'string[]' }],
    outputs: [{ name: '', type: 'bool[]', internalType: 'bool[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'makeCommitments',
    inputs: [
      { name: 'names', type: 'string[]', internalType: 'string[]' },
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'durations', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'secret', type: 'bytes32', internalType: 'bytes32' },
      { name: 'resolver', type: 'address', internalType: 'address' },
      { name: 'data', type: 'bytes[][]', internalType: 'bytes[][]' },
      { name: 'reverseRecord', type: 'bool', internalType: 'bool' },
      { name: 'ownerControlledFuses', type: 'uint16', internalType: 'uint16' },
    ],
    outputs: [{ name: '', type: 'bytes32[]', internalType: 'bytes32[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'multiCommit',
    inputs: [{ name: 'commitments', type: 'bytes32[]', internalType: 'bytes32[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'multiRegister',
    inputs: [
      { name: 'names', type: 'string[]', internalType: 'string[]' },
      { name: 'owner', type: 'address', internalType: 'address' },
      { name: 'durations', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'secret', type: 'bytes32', internalType: 'bytes32' },
      { name: 'resolver', type: 'address', internalType: 'address' },
      { name: 'data', type: 'bytes[][]', internalType: 'bytes[][]' },
      { name: 'reverseRecord', type: 'bool', internalType: 'bool' },
      { name: 'ownerControlledFuses', type: 'uint16', internalType: 'uint16' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'rentPrices',
    inputs: [
      { name: 'names', type: 'string[]', internalType: 'string[]' },
      { name: 'durations', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalPrice',
    inputs: [
      { name: 'names', type: 'string[]', internalType: 'string[]' },
      { name: 'durations', type: 'uint256[]', internalType: 'uint256[]' },
    ],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'NameRegistered',
    inputs: [
      { name: 'name', type: 'string', indexed: false, internalType: 'string' },
      { name: 'labelHash', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'owner', type: 'address', indexed: true, internalType: 'address' },
      { name: 'cost', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'duration', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'referrer', type: 'bytes32', indexed: true, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'RefundFailed', inputs: [] },
] as const
