export const PREMIUM = 'Premium'
export const REGISTERED = 'Registered'
export const UNREGISTERED = 'Available'
export const GRACE_PERIOD = 'Grace'

export const REGISTERABLE_STATUSES = [PREMIUM, UNREGISTERED]
export const REGISTERED_STATUSES = [REGISTERED, GRACE_PERIOD]
export const EXPIRED_STATUSES = [UNREGISTERED, GRACE_PERIOD, PREMIUM]
export const ALL_REGISTRATION_STATUSES = [PREMIUM, REGISTERED, UNREGISTERED, GRACE_PERIOD] as const
