import type { Meta, StoryObj } from '@storybook/nextjs-vite'

const componentFiles = [
  'src/app/[name]/components/PremiumPriceControls.tsx',
  'src/app/[name]/components/PremiumPriceGraph.tsx',
  'src/app/[name]/components/actions.tsx',
  'src/app/[name]/components/activity.tsx',
  'src/app/[name]/components/categories.tsx',
  'src/app/[name]/components/commentsPanel.tsx',
  'src/app/[name]/components/keywordMetrics.tsx',
  'src/app/[name]/components/listings.tsx',
  'src/app/[name]/components/metadata.tsx',
  'src/app/[name]/components/name.tsx',
  'src/app/[name]/components/offers.tsx',
  'src/app/[name]/components/primaryDetails.tsx',
  'src/app/[name]/components/register.tsx',
  'src/app/[name]/components/roles.tsx',
  'src/app/[name]/components/secondaryDetails.tsx',
  'src/app/[name]/components/similarNames.tsx',
  'src/app/analytics/components/AnalyticsChart.tsx',
  'src/app/analytics/components/AnalyticsContent.tsx',
  'src/app/analytics/components/AnalyticsFilters.tsx',
  'src/app/analytics/components/AnalyticsRow.tsx',
  'src/app/analytics/components/ChartsSection.tsx',
  'src/app/analytics/components/TopListCard.tsx',
  'src/app/analytics/components/TopListsSection.tsx',
  'src/app/bulk-search/components/domainPanel.tsx',
  'src/app/bulk-search/components/mainPanel.tsx',
  'src/app/bulk-search/components/tabSwitcher.tsx',
  'src/app/bulk-search/components/textareaSection.tsx',
  'src/app/categories/[category]/components/activity.tsx',
  'src/app/categories/[category]/components/category.tsx',
  'src/app/categories/[category]/components/categoryDetails.tsx',
  'src/app/categories/[category]/components/domains.tsx',
  'src/app/categories/[category]/components/holderRow.tsx',
  'src/app/categories/[category]/components/holders.tsx',
  'src/app/categories/[category]/components/main-panel.tsx',
  'src/app/categories/[category]/components/tabSwitcher.tsx',
  'src/app/categories/components/CategoriesFilterPanel/index.tsx',
  'src/app/categories/components/CategoriesPanel/index.tsx',
  'src/app/categories/components/CategoriesSortDropdown/index.tsx',
  'src/app/categories/components/CategoryTypeFilter/index.tsx',
  'src/app/categories/components/MainPanel/index.tsx',
  'src/app/categories/components/activity.tsx',
  'src/app/categories/components/allHolderRow.tsx',
  'src/app/categories/components/allHoldersPanel.tsx',
  'src/app/categories/components/categories.tsx',
  'src/app/categories/components/categoryCard.tsx',
  'src/app/categories/components/categoryRow.tsx',
  'src/app/categories/components/domainsPanel.tsx',
  'src/app/categories/components/tabSwitcher.tsx',
  'src/app/leaderboard/components/LeaderboardFilters.tsx',
  'src/app/leaderboard/components/LeaderboardList.tsx',
  'src/app/leaderboard/components/LeaderboardRow.tsx',
  'src/app/marketplace/components/actionButtons.tsx',
  'src/app/marketplace/components/activityPanel.tsx',
  'src/app/marketplace/components/domainPanel.tsx',
  'src/app/marketplace/components/mainPanel.tsx',
  'src/app/marketplace/components/tabSwitcher.tsx',
  'src/app/profile/[user]/components/actionButtons.tsx',
  'src/app/profile/[user]/components/activity.tsx',
  'src/app/profile/[user]/components/brokerPanel.tsx',
  'src/app/profile/[user]/components/details.tsx',
  'src/app/profile/[user]/components/domains.tsx',
  'src/app/profile/[user]/components/main-panel.tsx',
  'src/app/profile/[user]/components/offerPanel.tsx',
  'src/app/profile/[user]/components/profile.tsx',
  'src/app/profile/[user]/components/tabSwitcher.tsx',
  'src/components/activity/components/activityRow.tsx',
  'src/components/activity/components/event.tsx',
  'src/components/activity/components/loadingRow.tsx',
  'src/components/activity/components/name.tsx',
  'src/components/activity/components/price.tsx',
  'src/components/activity/index.tsx',
  'src/components/cart/components/actionButtons.tsx',
  'src/components/cart/components/domainItem.tsx',
  'src/components/cart/index.tsx',
  'src/components/chat/components/chat/composer.tsx',
  'src/components/chat/components/chat/dayDivider.tsx',
  'src/components/chat/components/chat/mentionDropdown.tsx',
  'src/components/chat/components/chat/messageRow.tsx',
  'src/components/chat/components/chat/threadView.tsx',
  'src/components/chat/components/chat/typingDots.tsx',
  'src/components/chat/components/chatRow.tsx',
  'src/components/chat/components/listView.tsx',
  'src/components/chat/components/new-chat/EFPFrineds.tsx',
  'src/components/chat/components/new-chat/newChatView.tsx',
  'src/components/chat/components/sendMessageButton.tsx',
  'src/components/chat/index.tsx',
  'src/components/chat/socketMount.tsx',
  'src/components/chat/utils/linkifyMessage.tsx',
  'src/components/comments/commentRow.tsx',
  'src/components/comments/composer.tsx',
  'src/components/comments/deleteCommentModal.tsx',
  'src/components/domains/actionsDropdown.tsx',
  'src/components/domains/grid/components/actions.tsx',
  'src/components/domains/grid/components/card.tsx',
  'src/components/domains/grid/components/gridLoadingRows.tsx',
  'src/components/domains/grid/components/loadingCard.tsx',
  'src/components/domains/index.tsx',
  'src/components/domains/sortDropdown.tsx',
  'src/components/domains/table/components/CartIcon.tsx',
  'src/components/domains/table/components/Price.tsx',
  'src/components/domains/table/components/RegistryPrice.tsx',
  'src/components/domains/table/components/TableLoadingRow.tsx',
  'src/components/domains/table/components/TableRow.tsx',
  'src/components/domains/table/components/actions.tsx',
  'src/components/domains/table/components/expiration.tsx',
  'src/components/domains/table/components/highestOffer.tsx',
  'src/components/domains/table/components/lastSale.tsx',
  'src/components/domains/table/components/name.tsx',
  'src/components/domains/viewSelector.tsx',
  'src/components/filters/ActivityFilter/TypeFilter/index.tsx',
  'src/components/filters/components/CategoriesCountFilter/index.tsx',
  'src/components/filters/components/CategoryFilter/index.tsx',
  'src/components/filters/components/CategoryFilterButtons/CategoryFilterAll.tsx',
  'src/components/filters/components/CategoryFilterButtons/CategoryFilterNone.tsx',
  'src/components/filters/components/CategoryFilterTab.tsx',
  'src/components/filters/components/CreationDateFilter/index.tsx',
  'src/components/filters/components/FilterDropdown.tsx',
  'src/components/filters/components/FilterSelector.tsx',
  'src/components/filters/components/Filters/index.tsx',
  'src/components/filters/components/LengthFilter/index.tsx',
  'src/components/filters/components/MarketFilter/index.tsx',
  'src/components/filters/components/NavLink.tsx',
  'src/components/filters/components/OfferFilter/index.tsx',
  'src/components/filters/components/PriceRangeFilter/components/PriceDenominatorSwitch.tsx',
  'src/components/filters/components/PriceRangeFilter/index.tsx',
  'src/components/filters/components/StatusFilter/index.tsx',
  'src/components/filters/components/TextMatchFilter/TextMatchFilterItem.tsx',
  'src/components/filters/components/TextMatchFilter/index.tsx',
  'src/components/filters/components/TextNonMatchFilter/index.tsx',
  'src/components/filters/components/TypeFilter/TypeFilterDropdown.tsx',
  'src/components/filters/components/TypeFilter/index.tsx',
  'src/components/filters/components/UnexpandedFilter.tsx',
  'src/components/filters/components/ViewsFilter/index.tsx',
  'src/components/filters/components/WatchersFilter/index.tsx',
  'src/components/filters/index.tsx',
  'src/components/footer/components/extras.tsx',
  'src/components/footer/components/pages.tsx',
  'src/components/footer/components/sources.tsx',
  'src/components/footer/index.tsx',
  'src/components/home/bulkTools.tsx',
  'src/components/home/displayedCard.tsx',
  'src/components/home/frequentlyAskedQuestions.tsx',
  'src/components/home/heroSearch.tsx',
  'src/components/home/liveActivity.tsx',
  'src/components/home/recent-container/index.tsx',
  'src/components/home/recent-container/premium.tsx',
  'src/components/home/recent-container/registrations.tsx',
  'src/components/home/recent-container/sales.tsx',
  'src/components/home/testemonials.tsx',
  'src/components/home/topCategories.tsx',
  'src/components/home/twitterBot.tsx',
  'src/components/modal/index.tsx',
  'src/components/modal/list-settings/components/reset-slot-warning.tsx',
  'src/components/modal/list-settings/components/settings-input.tsx',
  'src/components/modal/list-settings/index.tsx',
  'src/components/modal/listing/cancelListingModal.tsx',
  'src/components/modal/listing/createListingModal.tsx',
  'src/components/modal/notifications/components/loadingRow.tsx',
  'src/components/modal/notifications/components/notificationRow.tsx',
  'src/components/modal/notifications/index.tsx',
  'src/components/modal/offer/acceptOfferModal.tsx',
  'src/components/modal/offer/cancelOfferModal.tsx',
  'src/components/modal/offer/createOfferModal.tsx',
  'src/components/modal/poap/claimPoap.tsx',
  'src/components/modal/purchase/buyNowModal.tsx',
  'src/components/modal/records/bulkEditRecordsModal.tsx',
  'src/components/modal/records/components/TransactionStatusRow.tsx',
  'src/components/modal/records/components/imageUploadModal.tsx',
  'src/components/modal/records/components/inputWithResolution.tsx',
  'src/components/modal/records/editRecordsModal.tsx',
  'src/components/modal/registration/components/collapsible-name-list.tsx',
  'src/components/modal/registration/components/committing-view.tsx',
  'src/components/modal/registration/components/cost-summary.tsx',
  'src/components/modal/registration/components/custom-owner-section.tsx',
  'src/components/modal/registration/components/error-view.tsx',
  'src/components/modal/registration/components/modal-backdrop.tsx',
  'src/components/modal/registration/components/name-carousel.tsx',
  'src/components/modal/registration/components/per-name-duration-editor.tsx',
  'src/components/modal/registration/components/registering-view.tsx',
  'src/components/modal/registration/components/registration-toast.tsx',
  'src/components/modal/registration/components/reverse-record.tsx',
  'src/components/modal/registration/components/review-form.tsx',
  'src/components/modal/registration/components/success-toast.tsx',
  'src/components/modal/registration/components/success-view.tsx',
  'src/components/modal/registration/components/waiting-view.tsx',
  'src/components/modal/registration/index.tsx',
  'src/components/modal/renewal/extendModal.tsx',
  'src/components/modal/search/components/loading-rows/categoryLoadingRow.tsx',
  'src/components/modal/search/components/loading-rows/nameLoadingRow.tsx',
  'src/components/modal/search/components/loading-rows/userLoadingRow.tsx',
  'src/components/modal/search/globalSearchModal.tsx',
  'src/components/modal/settings/settingsModal.tsx',
  'src/components/modal/share/shareModal.tsx',
  'src/components/modal/transfer/transferModal.tsx',
  'src/components/navigation/cart.tsx',
  'src/components/navigation/chats.tsx',
  'src/components/navigation/dropdowns/categories.tsx',
  'src/components/navigation/dropdowns/explore.tsx',
  'src/components/navigation/dropdowns/leaderboard.tsx',
  'src/components/navigation/dropdowns/more.tsx',
  'src/components/navigation/dropdowns/premium.tsx',
  'src/components/navigation/hamburger.tsx',
  'src/components/navigation/index.tsx',
  'src/components/navigation/notifications.tsx',
  'src/components/navigation/pages.tsx',
  'src/components/navigation/searchIcon.tsx',
  'src/components/navigation/watchlist.tsx',
  'src/components/offers/components/actions.tsx',
  'src/components/offers/components/expires.tsx',
  'src/components/offers/components/loadingRow.tsx',
  'src/components/offers/components/name.tsx',
  'src/components/offers/components/offerAmount.tsx',
  'src/components/offers/components/offerRow.tsx',
  'src/components/offers/components/offerrer.tsx',
  'src/components/offers/index.tsx',
  'src/components/posthog/posthog-group-sync.tsx',
  'src/components/posthog/posthog-identify.tsx',
  'src/components/posthog/posthog-pageview.tsx',
  'src/components/posthog/posthog-profile-properties.tsx',
  'src/components/posthog/posthog-provider.tsx',
  'src/components/ui/activityTime.tsx',
  'src/components/ui/animateIn.tsx',
  'src/components/ui/asset.tsx',
  'src/components/ui/bulkSelect.tsx',
  'src/components/ui/buttons/primary.tsx',
  'src/components/ui/buttons/secondary.tsx',
  'src/components/ui/buttons/signInButton/index.tsx',
  'src/components/ui/contextMenu.tsx',
  'src/components/ui/datepicker.tsx',
  'src/components/ui/downloadButton.tsx',
  'src/components/ui/dropdown.tsx',
  'src/components/ui/expandableTab.tsx',
  'src/components/ui/infoBar.tsx',
  'src/components/ui/input.tsx',
  'src/components/ui/label.tsx',
  'src/components/ui/loadingCell.tsx',
  'src/components/ui/loadingSpinner.tsx',
  'src/components/ui/nameImage.tsx',
  'src/components/ui/noResults.tsx',
  'src/components/ui/price.tsx',
  'src/components/ui/searchbar.tsx',
  'src/components/ui/setEmailReminder.tsx',
  'src/components/ui/tabSelector.tsx',
  'src/components/ui/textarea.tsx',
  'src/components/ui/tooltip.tsx',
  'src/components/ui/user.tsx',
  'src/components/ui/virtualgrid.tsx',
  'src/components/ui/virtuallist.tsx',
  'src/components/ui/watchlist.tsx',
] as const

const groupedComponentFiles = componentFiles.reduce<Record<string, string[]>>((groups, file) => {
  const section = file.startsWith('src/app/') ? 'App Components' : 'Shared Components'
  groups[section] = [...(groups[section] ?? []), file]
  return groups
}, {})

const ComponentInventory = () => (
  <section className='text-foreground mx-auto flex max-w-5xl flex-col gap-6'>
    <header className='border-tertiary bg-secondary flex flex-col gap-2 rounded-2xl border p-6 shadow-lg'>
      <p className='text-neutral text-sm tracking-[0.3em] uppercase'>Storybook Coverage</p>
      <h1 className='text-3xl font-semibold'>Component Inventory</h1>
      <p className='text-md text-neutral max-w-3xl leading-6'>
        This story tracks every component file under <code>src/components</code> and page-local component folders under{' '}
        <code>src/app/**/components</code>. Use it as the coverage checklist while adding or reviewing focused component
        stories.
      </p>
      <div className='text-primary text-lg'>{componentFiles.length} component files covered</div>
    </header>

    {Object.entries(groupedComponentFiles).map(([section, files]) => (
      <article key={section} className='border-tertiary bg-secondary rounded-2xl border p-6'>
        <h2 className='mb-4 text-xl font-semibold'>{section}</h2>
        <div className='grid gap-2 md:grid-cols-2'>
          {files.map((file) => (
            <code key={file} className='bg-background text-neutral rounded-lg px-3 py-2 text-xs'>
              {file}
            </code>
          ))}
        </div>
      </article>
    ))}
  </section>
)

const meta = {
  title: 'Component Inventory/All Components',
  component: ComponentInventory,
  parameters: {
    layout: 'fullscreen',
  },
} satisfies Meta<typeof ComponentInventory>

export default meta

type Story = StoryObj<typeof meta>

export const AllComponents: Story = {}
