import { nameHasEmoji, nameHasNumbers } from './nameCharacters'

export const generateEmptyName = (name: string, tokenId: string) => ({
  id: 0,
  name,
  token_id: tokenId,
  expiry_date: null,
  registration_date: null,
  creation_date: null,
  owner: null,
  metadata: {},
  has_numbers: nameHasNumbers(name),
  has_emoji: nameHasEmoji(name),
  listings: [],
  clubs: [],
  club_ranks: null,
  highest_offer_wei: null,
  highest_offer_id: null,
  highest_offer_currency: null,
  last_sale_price_usd: null,
  offer: null,
  last_sale_price: null,
  last_sale_currency: null,
  last_sale_date: null,
  view_count: 0,
  watchers_count: 0,
  downvotes: 0,
  upvotes: 0,
  watchlist_record_id: null,
})
